- example/src/App.tsx
- package.json
- src/index.ts
- src/pid/index.ts
- src/pid/issuing.ts
- src/sd-jwt/index.ts
- src/sd-jwt/types.ts
- src/utils/dpop.ts
- src/utils/errors.ts
- src/utils/signature.ts
- src/wallet-instance-attestation/issuing.ts
- yarn.lock
Adds the integration towards the PID issuer for obtaining a PID credential.
- Added `PAR` request with JWT generator
- Added `auth token` request with DPoP generator
- Added `credential` request with proof on nonce generator
This PR ports the SDK made only for Android into typescript code
Tested locally and through unit tests
To understand how to get a PID refer to the `getPid` function within the sample app.
> feat: PID issuing [SIW-313]

- example/package.json
- example/src/scenarios/cross-device-flow-with-rp.tsx
- example/yarn.lock
- package.json
- src/rp/index.ts
- src/utils/errors.ts
- yarn.lock
* encrypt authorization response
As described in https://italia.github.io/eudi-wallet-it-docs/v0.4.1/en/relying-party-solution.html#authorization-response-details, authorization response payload must be encrypted in order to avoid SSL split attack vulnerabilities. 
Encryption has been made according to OpenID4VP specification https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#name-signed-and-encrypted-respon
> feat: [SIW-351] Encrypt authorization response

- example/src/scenarios/cross-device-flow-with-rp.tsx
- src/rp/index.ts
* add jwt signature verification
Check if the incoming Request Object is authentic
> feat: [SIW-337] Verifiy Request Object signature

- example/src/scenarios/cross-device-flow-with-rp.tsx
- package.json
- src/index.ts
- src/rp/types.ts
- src/trust/__tests__/index.test.ts
- src/trust/types.ts
* fix `EntityConfiguration` and `RpEntityConfiguration` parsers so they don't strip unknown keys
* set `federation_entity` attributes as optional, according to https://openid.net/specs/openid-connect-federation-1_0.html#appendix-A.2.2-5
* skip trust chain verification as it's not resolved yet by the test Relying Party
* expose `EntityConfiguration`, `TrustAnchorEntityConfiguration` and `RpEntityConfiguration` types
Bugs were introduced in https://github.com/pagopa/io-react-native-wallet/pull/34 as the entity configurations failed to be parsed. This is due to a misinterpreted feature of `zod` that [automatically strips additional fields on objects](https://github.com/colinhacks/zod/tree/v2#migration-from-v1).
Example app
> Fix #34 Entity Configuration parsing

- example/ios/example.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
This pull request eliminates the outdated example xcworkspace which is no longer needed.
When attempting to execute `yarn ios` on the example app, React Native throws an error due to the obsolete xcworkspace, resulting in a failure to locate a project with that particular name. This problem arises as a consequence of the refactoring carried out in pull request #36. However, by removing the outdated xcworkspace, React Native will correctly interpret the xcworkspace with the updated name, `IoReactNativeWalletExample.xcworkspace`.
Run `yarn ios` and the example app should now build without throwing an error.
> build: [SIW-494] Remove old example xcworkspace

- example/android/app/src/main/AndroidManifest.xml
- example/ios/IoReactNativeWalletExample/AppDelegate.mm
- example/ios/IoReactNativeWalletExample/Info.plist
- example/ios/Podfile.lock
- example/package.json
- example/src/App.tsx
- example/src/scenarios/cross-device-flow-with-rp.tsx
- example/src/scenarios/index.tsx
- example/yarn.lock
Adds integration to the `eudiw://` deeplink to test the same device authentication scenario towards RP.
⚠️ Warning: Only for the example app a deep link (eudiw://) was used but for future versions a universal link will be used as decided within the RFC.
- Added handler for `eudiw://` deep link which automatically starts the authentication flow towards RP.
This PR was necessary as it is no longer possible to use dated **QR Codes** (therefore hard coded in the app) as they are expired but a fresh session must be used. The implementation of the **same device flow** allows you to avoid using the camera on the simulator to obtain the content of the QR Code.
Tested on real devices and simulators on iOS and Android
https://github.com/pagopa/io-react-native-wallet/assets/442709/8cd1c17c-fe4a-4985- …
> feat: [SIW-559] Add deep link handler for cross device scenario in example App

- package.json
- src/index.ts
In https://github.com/pagopa/io-react-native-wallet/pull/43 we decided to not expose entity configuration types, as they might be inferred. In https://github.com/pagopa/io-app/pull/5039#discussion_r1340274555 it comes up they are useful, so in this PR we make them available again.
> fix: [SIW-540] Restore exported types

- example/src/scenarios/get-pid.tsx
- package.json
- src/pid/issuing.ts
- src/utils/__tests__/decoder.test.ts
- src/utils/decoder.ts
Adds the call to the authorization endpoint to obtain the PID.
- Introduces a breaking change to `PID.Issuing.getCredential` and `PID.Issuing.authorizeIssuing`. In particular, the user data must be passed to `authorizeIssuing` and no longer to `getCredential`.
- Adds support for form_post as defined in https://github.com/italia/eudi-wallet-it-docs/issues/132
See https://github.com/italia/eudi-wallet-it-docs/issues/132
Unit tested and with simulator
> feat!: [SIW-545] Adds the authorization endpoint for PID issuing

- example/src/scenarios/cross-device-flow-with-rp.tsx
- package.json
- src/credential/issuance/01-start-flow.ts
- src/credential/presentation/01-start-flow.ts
- src/utils/misc.ts
* `StartFlow` as sync function
* `Out` to handle both sync and async functions
`StartFlow` is a generic function signature that maps any touchpoint the User can use to start the Issuance and Presentation processes. It was introduced in #62.
Touchpoint may be:
* QR code scanning (cross-device)
* Select an element from a list (same device)
* URL decode (same device)
We found out it's better to keep it synchronous
Type system check
> fix!: [SIW-631] `StartFlow` to be syncronous

- package.json
For some reasons GitHub actions started to fail. It seems to be linked to https://github.com/yarnpkg/yarn/issues/9015, but I couldn't prove it.
kudos to @sebbalex for the hint!
> chore: Pin `yarn` version

- src/credential/issuance/07-verify-and-parse-credential.ts
Co-authored by @balanza 
Converts the list of disclosures key-value pairs into an object before constructing the list of attributes that are not defined in the issuer configuration.
This change fixes an issue which occurs when the credential has disclosures not defined in the issuer configuration and the `ignoreMissingAttributes` is set to `true`. 
The issue is caused by a missing conversion of the disclosures key-value pairs into an object which causes a duplication of defined disclosures in the undefined list. 
This leads to an overwrite of the defined disclosure when the two lists are merged in the function return.
By testing the `mDL` issuance (SD-JTW). The verified and parsed credential should have each disclosures with a locale.
> fix: [SIW-762] Credential parsing with undefined attributes

- .gitignore
- example/.env.example
- example/babel.config.js
- example/ios/IoReactNativeWalletExample.xcodeproj/project.pbxproj
- example/package.json
- example/src/config.ts
- example/src/scenarios/create-wallet-instance.tsx
- example/yarn.lock
Adds reading the configuration file directly from the `.env` file for the **example app.** 
Avoiding hard-coded URLs.
> chore: Add `react-native-dotenv` for example app

- example/src/config.ts
- example/src/scenarios/create-wallet-instance.tsx
This PR adds the android example app for the `createWalletInstance` scenario.
- Use `Platform.select` to differentiate between the iOS and Android flow when generating the hardware key. The main difference is that on Android we generate the hardware-backed key via `io-react-native-crypto`.
Follow these steps to test the flow: 
- Run [io-func-wallet-solution-backend](https://github.com/pagopa/io-wallet/tree/master/apps/io-func-wallet-solution-backend). I can provide the required `local.settings.json` in private if necessary;
- Run the proxy server under `example/dev-proxy`. I can provide the required `.env` in private if necessary. Make sure that `API_HOST` corresponds to the address:port combination of the function started in the previous step (defaults to `http://localhost:7071`);
- Run …
> chore: [SIW-1160] Add Android example app

- example/src/scenarios/prepare-integrity-context.ts
- example/src/utils/integrity/integrity.android.ts
- example/src/utils/integrity/integrity.ios.ts
- src/utils/integrity.ts
- Edit `generateIntegrityHarwareKeyTag` to use the function exposed `io-react-native-jwt` to convert the `base64` key returned from the native method to `base64url`;
- Edit `getHardwareSignatureWithAuthData` and `getAttestation` to convert the `base64url` key used in this package to `base64` which is what `io-react-native-integrity` uses;
- Defines `getAttestation` for Android as well due to different implementation which previously converged into the same native method.
Currently, `io-wallet` might return a `500` while creating a wallet instance on iOS due to the hardware key tag being encoded in base64 and thus having characters which can't be stored on the underlying Cosmos DB.
This PR converts the `base64` key tag to `base64url` in the `IntegrityContext`, thus making it safe to be …
> chore: [SIW-1208] Use base64url for iOS integrity keys

- example/.env.example
- example/src/config.ts
- example/src/utils/fetch.ts
It introduces a utility within the example app to generate a `fetch` function that adds the **authentication token** read by the `env` to the **headers** of the request to the issuer.
> feat: [SIW-1255] Add issuer authentication

- example/src/scenarios/get-attestation.ts
- openapi/wallet-provider.yaml
- src/client/index.ts
- src/utils/errors.ts
- src/wallet-instance-attestation/issuing.ts
- src/wallet-instance/index.ts
- Added `WalletInstanceRevokedError`
- Added `WalletInstanceNotFoundError`
- Handle errors in `getAttestation`
When getting a Wallet Instance Attestation the server may respond with specific HTTP status codes that define the status of a Wallet Instance, i.e. revoked or not found.
The library now catches those status codes and maps them to more meaningful errors.
The example application was run with a proxy to intercept responses and change the HTTP status code.
> feat: [SIW 1190]: handle errors to determine a Wallet Instance status

- example/.env.example
- example/dev-proxy/app.py
- example/src/config.ts
- example/src/utils/fetch.ts
As it is structured, the dev-proxy only works by proxing the requests that arrive on the first path (e.g. `/path`) but does not manage multipaths (e.g. `/api/v1/path`). Since our simulated backend will have to be called on a different base path (`/api/v1/wallet`) this **basepath** has also been added to the dev server.
Furthermore, the names of the environment variables have been changed in accordance with what has already been defined in other PRs.
> fix: [SIW-1273] Fix dev-proxy and rename env variables

- example/.env.example
- example/ios/IoReactNativeWalletExample.xcodeproj/project.pbxproj
- example/src/App.tsx
- example/src/config.ts
- example/src/scenarios/component/TestCieL3Scenario.tsx
- example/src/scenarios/get-pid.ts
- src/cie/manager.ts
Adds the configuration to use dev or prod environment on the sample app by directly configuring the `.env`.
Now it is possible to set whether to use the `UAT` environment for CIE and specify the `SPID_IDPHINT` to use. Therefore it is not necessary to indicate the CIE idphint since it is known.
Example:
```
CIE_UAT='false'
SPID_IDPHINT='https://posteid.poste.it'
```
It also introduces some minor fixes.
> fix: [SIW-1324] Add prod configuration

- example/src/scenarios/component/TestCieL3Scenario.tsx
- example/src/scenarios/get-crendential.ts
- example/src/scenarios/get-pid.ts
- package.json
- src/credential/issuance/05-authorize-access.ts
- src/credential/issuance/06-obtain-credential.ts
- src/credential/issuance/const.ts
Fixes the use of DPoP and adds management of the dPoP crypto context. It should not introduce breaking change.
An ephemeral key is no longer used for each DPoP but the same key is recycled for each obtainment flow. Only at the end of obtaining the key is it deleted. If the flow is not successful, the same key can be reused.
> fix: Fix dPoP

- example/ios/Podfile.lock
This PR aligns the `Podfile.lock` of the iOS project.
Each time you run a `pod install` while cloning this repo, the `react-native-cie` dependency gets removed. This is intended because we have a script in our `package.json` to install and remove that package when needed. However we mistakenly committed the `Podfile.lock` after running the script which installs it.
N/A
N/A
> build: Align Podfile.lock

- example/src/App.tsx
- example/src/scenarios/get-crendential.ts
- Added `type` parameter to `get-credential` scenario
- Added Disability Card issuance button to the example app
This PR introduces the ability to obtain a Disability Card credential with the example app
Test the DC scenario and obtain a Disability Card credential 
N/A
> feat: [SIW-1439] Add Disability Card scenario to the example app

- package.json
This PR bumps the package version to `v0.16.0`.
> chore: Release v0.16.0

- example/ios/Podfile.lock
- example/src/screens/WalletInstanceScreen.tsx
- example/src/thunks/instance.ts
- Add alert when pressing `Create Wallet Instance` if a wallet instance already exists;
- Dispatch the instance reset action outside the thunk before creating a new one;
- [EXTRA] Update misaligned `Podfile.lock` caused by #130 
The loading spinner was not visible during the instance creation because the instance reset action was dispatched within the thunk. As a result, the instance's async state was reset to its initial state immediately after being set to loading, causing the spinner to disappear.
Try to create a wallet instance, the loading spinner should be visibile. Try to create it again and the app should show an alert. Then press "Ok" and the app should resets the whole state before creating a new instance.
> fix: [SIW-1516] Loading spinner not visibile when creating a wallet instance

- example/package.json
- example/src/components/TestCieL3Scenario.tsx
- example/src/store/reducers/credential.ts
- example/src/store/reducers/pid.ts
- example/src/thunks/pidCieL3.ts
- Add `await` when generating DPoP crypto keys;
- Add button to close CIE L3 modal on iOS as well; 
- Remove `pidCiel3FlowParams` from `credential` reducer which was wrongly left there;
- Add async status reset when dispatching `pidCiel3FlowReset` action in order to reset the loading state; 
- Fix `selectPidCieL3FlowParams` which was wrongly pointing to the `credential` reducer instead of `pid` reducer;
- Update the CIE DEV/PRO scripts in `package.json` to use `bundler` to run `pod install` which is now the advised way to do it;
This PR fixes the CIE L3 scenario failure caused by a DPoP key error. The root cause was an unawaited promise, leading to subsequent code attempting to use a cryptographic key that hadn't been generated yet. 
Test a CIE L3 flow. Remember to run `yarn cie-ios:prod` …
> fix: [SIW-1515] CIE L3 scenario DPoP key error in example apple

- src/credential/issuance/06-obtain-credential.ts
- src/utils/errors.ts
- Adds a specific error `CredentialNotEntitledError` when the credential issuer returns `404` in response to the `/credential` request;
- Adds a generic error `CredentialRequestError` for generic errors.
This PR adds a specific error which is raised when `/credential` response contains a `404` code which indicates the user is not entitled to receive the requested credential.
With a proxy map locally the `/credential` response to a `404` and check in the debug menu of the example app if the custom error is thrown.
> feat: [SIW-1558] Add not entiled error when requesting a credential

- src/credential/issuance/README.md
- Add the `201 Created` mapped status in the issuance context.
This PR updates the issuance `README.md` with a new mapped status code.
Preview the `README.md` file by previewing the branch changes in GitHub.
> docs: [SIW-1670] Update issuance README

- src/credential/issuance/07-verify-and-parse-credential.ts
- src/credential/issuance/README.md
- Pass `includeUndefinedAttributes` to `parseCredentialSdJwt`.
Currently it is possible to pass `includeUndefinedAttributes` to `verifyAndParseCredential`, but that parameter is lost in the internal function invocations, so it is not possible to get disclosures/claims that are not explicitly supported in the entity configuration.
> fix: [SIW-1679] Restore optional parameter to get all disclosures

- src/credential/issuance/07-verify-and-parse-credential.ts
- src/credential/issuance/README.md
- `verifyAndParseCredential` returns `iat` and `exp` claims as `issuedAt` and `expiration` respectively
We need to know the expiration and issuance date of credentials. The `exp` claim is included in the JWT payload, the `iat` is found among disclosures.
This PR attempts to expose those claims in a simple and backward-compatible way, adding them to the object returned by `verifyAndParseCredential`. Since this function is always called at the end of the issuance flow, it is convenient to also get some additional metadata without requiring another step of verification/decode later.
The use of `includeUndefinedAttributes` was discarded to avoid getting claims not declared in the issuer configuration.
> chore: [SIW-1684] Expose `iat` and `exp` claims

- src/credential/issuance/07-verify-and-parse-credential.ts
- `verifyAndParseCredential` can return an undefined `issuedAt`
Although SD-JWTs should always contain the `iat` claim, we cannot have the absolute certainty. This PR takes a safe approach and handles a missing `iat` claim among disclosures.
> chore: [SIW-1707] Handle undefined `iat`claim

- openapi/wallet-provider.yaml
- src/utils/errors.ts
- src/wallet-instance-attestation/README.md
- src/wallet-instance-attestation/issuing.ts
- src/wallet-instance/README.md
- src/wallet-instance/index.ts
- Update the `wallet-provider.yaml` specs due to changes in how the errors are mapped for certain endpoints like `/token` and `/wallet-instance`; 
- Create custom exceptions which are thrown when an error related to the integrity checks for `/token` and `/wallet-instances` fails, returning a `409` HTTP code; 
- Map these errors in their relative flows step for registering a wallet instance and obtaining an attestation.
This changes allows the consumer app to receive a custom error when an integrity check fails, thus allowing a specific text copy to be shown to the user.
- Open the example app and login; 
- Start a proxy like `Proxyman`;
- Try to register a wallet instance and obtain an attestation, everything should work just as before;
- Manually map the result of `/token` and …
> feat: [SIW-1591] Add 409 handling with custom exception for wallet provider

- example/ios/Podfile.lock
- example/package.json
- example/src/store/reducers/attestation.ts
- example/src/store/reducers/credential.ts
- example/src/store/reducers/pid.ts
- example/src/store/storage.ts
- example/src/store/store.ts
- example/src/thunks/credential.ts
- example/src/thunks/pid.ts
- example/src/thunks/pidCieL3.ts
- example/yarn.lock
This PR removes the need to get a new Wallet Instance Attestation every time there is a credential issuance.
Once the WIA is obtained, it is stored and persisted to the device via Secure Storage and then used for the credential issuance.  The WIA is obtained again only when it expires.
This PR also introduces Secure Storage for WIA, PID and Credentials persistance.
Since new WIA requests on Android requires a Play Integrity API call, this change is required to reduce the Play Integrity API usage.
Run the example app and check that the WIA is requested only once or when it is expired
> chore: [SIW-1632] Reuse the Wallet Instance Attestation in the example app

- src/credential/issuance/06-obtain-credential.ts
- src/credential/issuance/README.md
- src/credential/issuance/types.ts
- src/credential/status/02-status-attestation.ts
- src/credential/status/README.md
- src/credential/status/types.ts
- src/utils/__tests__/errors.test.ts
- src/utils/errors.ts
- src/utils/misc.ts
This PR creates the `CredentialInvalidStatusError` with `errorCode` to track specific errors in 403 and 404 responses during credential and status attestation requests, so that library consumers can extract more details on the failure. Ideally, this error code should be matched with one of the codes found in `issuance_errors_supported` in the EC to get the corresponding message.
> [!NOTE]
> The `CredentialNotEntitledError` and `StatusAttestationInvalid` have been superseded by `CredentialInvalidStatusError` as both those cases can be handled with a single error. 
- Renamed `StatusAttestationInvalid` to `CredentialInvalidStatusError` and added `errorCode`
- Removed `CredentialNotEntitledError`
- Added the response body in text format to `UnexpectedStatusCodeError`, otherwise the response …
> chore: [SIW-1779] Handle error codes during credential issuance and status attestation

- example/src/thunks/instance.ts
- openapi/wallet-provider.yaml
- src/client/__tests__/index.test.ts
- src/client/index.ts
- src/utils/error-codes.ts
- src/wallet-instance/README.md
- src/wallet-instance/index.ts
- Updated OpenAPI definitions (and removed `/wallet-instances/current/status`)
- Added `getWalletInstanceStatus` method
- Refactored `revokeCurrentWalletInstance` into `revokeWalletInstance` to accept the Wallet Instance ID
This PR introduces a new function to get the status of a Wallet Instance without requiring an attestation. The function to revoke a Wallet Instance was modified to be consistent with `getWalletInstanceStatus` and require the ID of the instance.
Used the new API client methods, and tried the other ones to ensure no regressions were introduced.
> feat: [SIW-1865] Add wallet instance status API call

- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- Changed `react-native-svg` version requirements in `package.json`
The current `react-native-svg` version is incompatible with the one required by the `react-native-qrcode-svg` package.
On Android, generate a Trustmark QR Code and check that everything works as expected.
> fix: Upgrade `react-native-svg` for `react-native-qrcode-svg` compatibility

- src/cie/component.tsx
Modified `WebViewComponent` in the CIE's flow.
This PR addresses the issue of the CIE read `completed` event being fired multiple times, potentially causing unexpected behaviors in a consumer that assumes the event is only emitted once.
Run the example app and ensure the CIE+PIN identification mode works as expected.
> fix: [SIW-1785] Avoid multiple CIE completed event

- package.json
- src/credential/presentation/04-retrieve-rp-jwks.ts
- src/credential/presentation/05-verify-request-object.ts
- src/credential/presentation/__tests__/04-retrieve-rp-jwks.test.ts
- src/credential/presentation/types.ts
- src/utils/crypto.ts
- yarn.lock
- Updated `types.ts `to include an optional `client_metadata` with `jwks_uri` and `jwks` fields for additional key information.
- Implemented certificate X.509 parsing and public key extraction in `04-retrieve-rp-jwks.ts` using `jsrsasign` and enhanced tests to cover new JWKS retrieval logic.
This PR aims to support X.509 certificates enables integration with systems that utilize certificate-based authentication.
> feat: [WLEO-228] Enhance Request Object Handling and JWKS Retrieval using x5c

- example/src/thunks/presentation.ts
- src/credential/presentation/01-start-flow.ts
- src/credential/presentation/03-get-request-object.ts
- src/credential/presentation/README.md
- src/credential/presentation/__tests__/01-start-flow.test.ts
- src/credential/presentation/errors.ts
- Change the `StartFlow` input parameters which now takes `requestUri` and `clientId` instead of the whole URL, giving the consumer app the responsibility to parse the URL;
- Update tests.
This change is needed because the URL is already parsed and validated by the consumer app.
Test a presentation flow.
> refactor: [WLEO-241] Presentation StartFlow input parameters 

- src/credential/presentation/07-evaluate-input-descriptor.ts
- src/credential/presentation/__tests__/07-evaluate-input-descriptor.test.ts
During evaluate-input-descriptor phase, introduced a new property `unrequestedDisclosures` to the EvaluatedDisclosures type to categorize disclosures that are neither required nor optional. When limit_disclosure is set to `required`, unrequestedDisclosures is empty, otherwise it contains disclosures that are not requested inside presentation_definition.
The introduction of `unrequestedDisclosures` addresses the need for a more granular categorization of disclosures in the credential presentation process. Previously, disclosures were limited to being either required or optional, which did not account for scenarios where certain disclosures should neither be mandatory nor suggested.
> feat: [WLEO-218] Introduce unrequestedDisclosures for enhanced disclosure categorization

- src/trust/types.ts
This PR eliminates the attributes that aren't passed from the credential issuer entity configuration after verifying the technical specifications. Specifically, it removes optional attributes that are not specified in the technical rules.
In other cases, the optional attribute has been removed because the attribute is being passed.
Since these attributes are neither passed in the entity configuration nor specified in the technical rules, they can be safely removed.
This change is required to ensure that the entity configuration we receive is consistent with the one we subsequently parse
You should be able to obtain PID and credentials
> chore: [SIW-1268] Deletion of optional attributes from the credential issuer entity configuration 

- src/credential/presentation/08-send-authorization-response.ts
- src/credential/presentation/types.ts
- `state` claim is now optional in Request Object schema
- `state` will be added in remote presentation if it is present in  Request Object
This PR aims to fix the mandatory of `state` claim in  Request Object. [OID4VP](https://openid.net/specs/openid-4-verifiable-presentations-1_0-20.html#name-authorization-request) and I[talian Specs](https://italia.github.io/eudi-wallet-it-docs/v0.9.2/en/relying-party-solution.html#authorization-request-details) mark it as optional or recommended, not mandatory.
During Interop Test in Utrecht, a Relying Party did not include state inside its Request Object. You can try to test when it is present at https://verifier.eudiw.dev/.
> fix:[WLEO-277] State must be optional in Request Object and Presentation Response

- openapi/wallet-provider.yaml
- src/wallet-instance/index.ts
> [!NOTE]  
> I updated the whole `wallet-provider.yaml` file based on the backend specifications.
- Add `getCurrentWalletInstanceStatus` API call to fetch the current wallet instance status
- Update wallet-provider yaml file
We need to check whether a user has an active wallet instance or not. As a result, the previous endpoint that checked WI based on `id` was inadequate.
> feat: [SIW-2048] Add current wallet instance status API call 

- src/credential/issuance/04-complete-user-authorization.ts
- src/credential/issuance/__tests__/04-complete-user-authorization.test.ts
- made the `idpHint` parameter in the `buildAuthorizationUrl` function optional by updating its type definition and usage.
- added tests for `buildAuthorizationUrl` function
To obtain an L3 PID, the `idphint` parameter must be omitted from the authentication request URL.
This pull request updates the `buildAuthorizationUrl` function to make the idpHint parameter optional, allowing authentication requests to be generated without explicitly setting an IdP hint when necessary.
Unit tests
> chore: [SIW-2197] Make `idphint` parameter optional for auth request url

- src/utils/__tests__/crypto.test.ts
- src/utils/crypto.ts
> [!WARNING]
> Breaking change for IT Wallet!
- New helper function, `fixBase64WithLeadingZero` (with its underlying helper, `removeLeadingZeroAndParseB64Url`), to sanitize JSON Web Key (JWK) properties. It addresses potential issues with cryptographic operations by processing the base64url encoded key components (x, y, e, and n). The new functions decode the input, remove any unwanted leading zero, and then re-encode the result to ensure proper formatting. 
- It replace `fixBase64EncodingOnKey` inside `CryptoContext`
The method `getPublicKey` in the `io-react-native-crypto` library returns a key with coordinates in base64 format. This base64 format is generated by converting hex to base64 internally, but sometimes the conversion does not conform to the P-256 key standard—which requires …
> fix: [WLEO-339] Add function to remove leading zero from base64url encoded JWK properties

- src/credential/issuance/06-obtain-credential.ts
- src/credential/issuance/__tests__/06-obtain-credential.test.ts
- Added an optional parameter `operationType` to the `obtainCredential` method to distinguish the issuing phase
- Added `operationType` to the `header` in the `/credential` request for the `re-issuing` flow
This PR aims to update the `obtainCredential` method for the transition from Documenti su IO to IT Wallet.
It is essential to distinguish between a standard `issuing` request and a `re-issuing` request.
It is currently not possible to test the credential flow in the re-issuing mode
> feat: [SIW-2196] Update ObtainCredential for IT Wallet transition

- src/credential/presentation/08-send-authorization-response.ts
- src/credential/presentation/__tests__/08-send-authorization-response.test.ts
- Updated `choosePublicKeyToEncrypt` function to prioritize **EC** keys (P-256, P-384) over **RSA** keys when selecting encryption keys from the JWKS.
- Filtered keys by use: "enc" and sorted them by type and curve support.
- Added a new unit test to verify that the function selects the first supported EC key.
This change ensures compatibility with `io-react-native-jwt`, which guarantees supports only for EC encryption keys with curves `P-256` and `P-384`. The previous implementation defaulted to the first enc key without prioritizing supported types, which could lead to runtime errors or unexpected behavior. By explicitly preferring compatible EC keys, we improve reliability and interoperability with supported clients.
> feat: [WLEO-345] Prioritize EC keys first P256 during Remote Presentation enc

- example/src/thunks/presentation.ts
- src/credential/presentation/01-start-flow.ts
- src/credential/presentation/03-get-request-object.ts
- src/credential/presentation/README.md
- src/credential/presentation/__tests__/01-start-flow.test.ts
- Use snake case for the presentation parameters in `startFlowFromQR`
- Updated tests
This PR changes the case of input parameters and validated parameters to `snake_case` in `startFlowFromQR`. The rationale is to provide consistency when validating the raw parameters extracted from a QR code or a deep link, without additional mapping between `snake_case` and `camelCase`.
`startFlowFromQR` has also been updated to accept null values, moving all the validation to the function, even for missing/nullable values.
Start a presentation flow with the example app. Everything should work as before.
> chore: [SIW-2287] Use snake case for presentation parameters in `startFlowFromQR`

- example/src/navigator/MainStackNavigator.tsx
- example/src/utils/environment.ts
- example/src/utils/logging.ts
- src/credential/issuance/06-obtain-credential.ts
- src/credential/issuance/07-verify-and-parse-credential.ts
- src/credential/status/02-status-attestation.ts
- src/credential/status/03-verify-and-parse-status-attestation.ts
- src/utils/par.ts
- src/wallet-instance-attestation/issuing.ts
- src/wallet-instance/index.ts
- Fix a few logging strings which were not printed out correctly;
- Updates the logging context creation logic which now sets the custom remote transport only when a remote address is provided.
This PR fixes a few broken logging strings and also the logging context creation which now doesn't set the custom remote transport if a remote address hasn't been provided.
- Uninstall the app;
- Reinstall the app;
- Try a random flow. The `TypeError` printed before each log in the console shouldn't appear if no address has been provided.
> fix: [WLEO-351,WLEO-352] Logging strings and remote server setting

- example/src/screens/CredentialScreen.tsx
- example/src/store/reducers/credential.ts
- example/src/store/types.ts
- example/src/thunks/presentation.ts
- example/src/utils/ui.ts
- src/credential/issuance/06-obtain-credential.ts
As explained below by Copilot.
This PR aims to add the support of obtaining the new credential type eu.europa.ec.eudi.hiid.1. It is needed to update the credential request body to conditionally use the "doctype" key for the "mso_mdoc" format.
1. Navigate to "Credentials"
2. Click on "Get credential (HealthID)
> feat: [WLEO-353] Support for obtaining the new credential type eu.europa.ec.eudi.hiid.1

- example/src/screens/PresentationScreen.tsx
- example/src/thunks/presentation.ts
- src/credential/presentation/03-get-request-object.ts
- src/credential/presentation/05-verify-request-object.ts
- src/credential/presentation/07-evaluate-dcql-query.ts
- src/credential/presentation/08-send-authorization-response.ts
- src/credential/presentation/README.md
- src/credential/presentation/__tests__/05-verify-request-object.test.ts
- src/credential/presentation/__tests__/07-evaluate-dcql-query.test.ts
- src/credential/presentation/__tests__/08-send-authorization-response.test.ts
- src/credential/presentation/errors.ts
- src/credential/presentation/index.ts
- src/credential/presentation/types.ts
- src/utils/__tests__/errors.test.ts
- src/utils/error-codes.ts
- src/utils/errors.ts
- Added `sendAuthorizationErrorResponse` function to notify the RP
- Created `RelyingPartyResponseError` class with RP-specific error codes
- Explicitly handled 400 and 403 HTTP status code when sending the Authorization Response
- Thrown `InvalidRequestObjectError` in `verifyRequestObject` for validation-related errors
- Thrown `DcqlError` in `evaluateDcqlQuery` to unify DCQL-related errors
- Refactored some error related utils and types
- Updated the example app
- Added more tests
This PR improves the error handling in the presentation flow, by providing a specific `RelyingPartyResponseError` and a function to notify the Relying Party of any errors occurred when processing the Authorization Request.
Tested against the test Relying Party instance, using the example app and a proxy to …
> feat: [SIW-2159] Handle presentation errors

- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
- src/mdoc/index.ts
- yarn.lock
- Update `io-react-native-cbor` to version `1.4.0`;
- Change the `keyId` parameter to `x5chain`. Currently only the first certificate in the chain is used.
This PR updates `io-react-native-cbor` to the latest version to avoid conflicts while installing this library alongside `io-react-native-proximity` due to a shared dependency.
Try to obtain a mDL. The parsing should succeed.
> deps: [WLEO-439] Update CBOR and x5chain parameter when verifying credential 

- src/credential/presentation/07-evaluate-input-descriptor.ts
- src/credential/presentation/__tests__/07-evaluate-input-descriptor.test.ts
This PR changes the behavior of the `evaluateInputDescriptorForMdoc` and `evaluateInputDescriptorForSdJwt4VC` methods to solve a bug regarding presentations containing only optional values.
- `src/credential/presentation/__tests__/07-evaluate-input-descriptor.test.ts`, `src/credential/presentation/__tests__/07-evaluate-input-descriptor.ts` : made the methods `evaluateInputDescriptorFor*` has been changed to throw in case no matches are found for a credential, optional or not. Tests have been modified accordingly.
The `findCredentialSdJwt` and `findCredentialMdoc` use their corresponding `evaluateInputDescriptorFor*` methods' logic to handle matching of the input descriptor with a credential's claims, more precisely they switch to the next credential upon the method throwing an error, and …
> fix: [WLEO-439] Changed behavior of evaluateInputDescriptor helper functions to throw on no match

- .github/workflows/publish.yaml
- Edit the `publish.yaml` workflow
This PR allows publishing to NPM under arbitrary prerelease tags (es. `next`, `rc`). The prerelease tag is dinamically extracted from the version in `package.json`.
The rationale is to allow publishing unstable versions to NPM without overriding the `latest` tag.
> ci: [SIW-2534] allow publishing to NPM under a prerelease tag

- __mocks__/@pagopa/io-react-native-jwt/index.ts
- src/credential/issuance/07-verify-and-parse-credential.ts
- src/credential/issuance/__tests__/07-verify-and-parse-credential.test.ts
- src/credential/status/03-verify-and-parse-status-assertion.ts
This PR enhances the `verifyCredentialSdJwt` function by replacing the kid string comparison with a more robust thumbprint-based key comparison.
This change replaces the kid comparison with a JWK thumbprint check to ensure reliable holder binding verification, avoiding mismatches due to inconsistent or missing kid values. It improves robustness and aligns with best practices.
- Test a complete issuing flow obtaining PID + Credentials
> fix: [SIW-2785] Improve kid string comparison with thumbprint-based key comparison on credential flow

- example/.env.example
- src/trust/types.ts
- Update `ClaimsMetadata` zod type
This PR fixes the zod type for [claims path pointer](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-15.html#appendix-C) in the Credential Issuer's Entity Configuration. The `path` property now supports strings, numbers and null values.
Fetched the EAA Entity Configuration in `pre` and ensured the parsing succeeded.
> fix: [SIW-2800] zod type for claims path pointer

- src/credential/presentation/07-evaluate-dcql-query.ts
- src/credential/status/02-status-assertion.ts
- src/credential/status/03-verify-and-parse-status-assertion.ts
- src/sd-jwt/types.ts
- src/trust/types.ts
- src/utils/credentials.ts
- The status assertion functions now accept the legacy `vc+sd-jwt` as format
- The constant LEGACY_SD_JWT has been created to better distinguish the legacy format
For backward-compatibility reasons the status assertion functions need to work with legacy credentials. Currently the format type is extracted dynamically from the `obtainCredential`'s return type, that only encompasses the new formats.
The issue is only at the types level, as the compiled code properly handles the old format.
> fix: [SIW-2859] Format type for backward-compatible status assertion
