- .eslintrc.js
> Use PagoPA lint rules

- .github/workflows/code-review.yaml
- .npmrc
- README.md
- example/ios/Podfile.lock
- example/package.json
- example/src/App.tsx
- example/yarn.lock
- package.json
- src/index.ts
- src/utils/errors.ts
- src/wallet-instance-attestation/index.ts
- src/wallet-instance-attestation/issuing.ts
- yarn.lock
Adds Wallet Instance integration and issuing.
- Added Wallet Instance Attestation Request
- Added Wallet Instance issuing
- Changed default npm registry
- Added example app with TEE
unit tested and tested on simulator
> feat: Add Wallet Instance Attestation issuing [SIW-314,315]

- package.json
- src/index.ts
- src/rp/__test__/index.test.ts
- src/rp/index.ts
- src/rp/types.ts
- src/utils/dpop.ts
- src/utils/errors.ts
- src/utils/signature.ts
- src/wallet-instance-attestation/issuing.ts
Adds integration for authentication to RP.
The `Authorization Response Details` are missing
- Add `decodeAuthRequestQR`
- Add `getUnsignedWalletInstanceDPoP`
- Add `getRequestObject`
Unit tested
> feat: Add RP authentication

- example/src/App.tsx
- example/src/scenarios/cross-device-flow-with-rp.tsx
- example/src/scenarios/index.tsx
* add test case
Implement a test case for the [Cross-device flow](https://italia.github.io/eudi-wallet-it-docs/v0.4.1/en/relying-party-solution.html#remote-cross-device-flow)
The test case is incomplete as it ends with obtaining the request object from the Relying Party. Other steps to be implemented in next PRs
> chore: [SIW-271] Cross-device flow test in example app

- example/src/scenarios/cross-device-flow-with-rp.tsx
- src/rp/index.ts
- src/rp/types.ts
* added methods to prepare and send the authorization response with disclosed data
* finalized the cross-device authorization scenario
In the process of cross-device authorization of the wallet with a RP, we elaborate and send the authorization response to finalize the process.
> feat: [SIW-336] Send authorization response to RP

- src/sd-jwt/__test__/index.test.ts
* new test data 
Test data more adherent to our current specs
> chore: fix SD-JWT tests

- example/ios/Podfile.lock
- package.json
- src/pid/__tests__/issuing.test.ts
- src/pid/issuing.ts
- src/pid/metadata.ts
- src/utils/errors.ts
- yarn.lock
Adds function below Issuer for getting metadata.
- Added `PID.Issuer.getMetadata()`
Unit tested
> chore: Add function to obtain PID issuer metadata [SIW-396]

- example/android/app/build.gradle
> fix: Update build.gradle

- package.json
- src/pid/issuing.ts
- src/pid/metadata.ts
Makes small changes to the PID types as established by the new technical rules 0.5.1. This modification does not bring any breaking change.
Tested locally and unit tested
> chore: [SIW-539] Update PID to 0.5.1 tech rules

- package.json
- src/wallet-instance-attestation/issuing.ts
* verify wallet instance attestation jwt.
Before finalizing the Wallet Instance Attestation issuing process, we validate the just received attestation by verifying:
* its signature is compliant with what exposed by the Wallet Provider Entity Configuration
* the token has not expired
* the claims contain correct wallet provider data
> feat: [SIW-323] Verify Wallet Instance Attestation on receving

- package.json
- src/utils/crypto.ts
Solves the bug in https://github.com/pagopa/io-react-native-wallet/pull/51#discussion_r1350312594
> fix: [SIW-584] Fix `finally` expression

- src/utils/__tests__/crypto.test.ts
- src/utils/crypto.ts
It was so easy I'm ashamed I didn't think about it
> Small syntax fix

- src/trust/types.ts
* add `organization_name` field
To comply to specifications: https://openid.net/specs/openid-connect-federation-1_0-29.html#name-federation-entity
> feat: [SIW-644] Added missing field to `federation_entity` section on entity statements

- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
This PR updates `@pagopa/io-react-native-jwt` to version `1.2.0` in both the library and the example application.
The example application has been run on the iOS Simulator and the Android Emulator.
> chore: [SIW-1098] Update io-react-native-jwt to `1.2.0`

- example/proxy.py
This PR add a proxy script in python to simulate `io-backend` proxy for user authentication
> chore: Create a proxy script to simulate io-backend in example app

- src/credential/issuance/03-start-user-authorization.ts
- src/credential/issuance/04-complete-user-authorization.ts
- src/credential/issuance/05-authorize-access.ts
- src/credential/issuance/06-obtain-credential.ts
This PR changes import from `../../../src` to `../../` where necessary. 
The import going from `../../../src` might cause problems with `jest` when importing this library.  
Static tests and check for regressions in existing flows
> fix: [SIW-1333] Wrong imports from utils folder

- src/credential/issuance/04-complete-user-authorization.ts
This PR changes import from `../../../src` to `../../` in `04-complete-user-authorization.ts`. 
The import going from ../../../src might cause problems with jest when importing this library.
Static tests.
> fix: [SIW-1368] Wrong import in complete authorisation during issuance

- src/credential/issuance/07-verify-and-parse-credential.ts
Add a `includeUndefinedAttributes` attribute to the verify and parse step which defaults to `false` and allows the inclusion of attributes not defined in the entity configuration when parsing a credential. No changes are required when calling this function, however this changes the default behaviour which now ignore them.
The attributes not included in the entity configuration must not be shown to the user and thus included in the parsed credential.
Static tests.
> chore[SIW-1373]: Do not include undefined attributes by default

- example/src/scenarios/get-credential-status-attestation.ts
- src/credential/status/02-status-attestation.ts
- src/credential/status/03-verify-and-parse-status-attestation.ts
- src/credential/status/index.ts
- src/credential/status/types.ts
- Add a `verifyAndParseStatusAttestation` function which verifies the signature of the status attestation by using the EC and parses it;
- Update the example scenario.
The verification and parsing of the status attestation is needed in order for the consumer of this library to use it.
Test a status attestation issuance after obtaining a MDL. Check the console logs for the parsed attestation.
> feat: [SIW-1499] Add status attestation verification and parsing

- package.json
This PR adds `js-sha256` as a direct dependency as it is required by the status attestation flow.
This allows the consumer not to worry about installing the dependency.
Static tests.
> fix: [SIW-1507] Add js-sha256 in library dependencies

- package.json
Depends on #125 
This PR bumps the package version to v0.16.1.
> chore: Release v0.16.2

- README.md
- example/README.md
- src/cie/README.md
- src/credential/issuance/README.md
- src/credential/presentation/README.md
- src/credential/status/README.md
- src/wallet-instance-attestation/README.md
- src/wallet-instance/README.md
Updates or creates the `README.md` of the main repository, the example app and each flow.
This PR adds a bit of documentation to the main repository, the example app and the library flows. This should make clear how flows should be structured, along with schemas and examples. The main goal is to give an overview given that the code is already well documented. 
You can check the preview by navigating the repo pointing at [this branch](https://github.com/pagopa/io-react-native-wallet/tree/SIW-1529-update-documentation).
> docs: [SIW-1529] Update documentation

- example/src/components/TestScenario.tsx
- example/src/screens/WalletInstanceScreen.tsx
- example/src/store/reducers/instance.ts
- example/src/thunks/instance.ts
- openapi/wallet-provider.yaml
- src/wallet-instance/README.md
- src/wallet-instance/index.ts
- Added new method `revokeCurrentWalletInstance`
- Added OpenAPI documentation for the new endpoint
- Updated the documentation
- Updated the example app
This PR adds a new method to revoke the active wallet instance of the user who sends the request.
> feat: [SIW-1704] Add method to revoke the current wallet instance

- src/trust/types.ts
Added `issuance_errors_supported` to the supported credentials configuration in the EC.
Support dynamic error messages for each credential.
Get a credential. Everything should work as expected, `issuance_errors_supported` is optional.
> chore: [SIW-1777] Validate and type `issuance_errors_supported`

- __mocks__/@pagopa/io-react-native-jwt/index.ts
- package.json
- yarn.lock
This PR upgrsdes the `io-react-native-jwt` dependency version
The updates allow to correctly decode UTF-8 string
Run the example app and check that you are able to obtain a credential
> chore: [SIW-1737] Upgrade `io-react-native-jwt` dependency package

- src/credential/trustmark/__tests__/get-credential-trustmark.test.ts
- src/credential/trustmark/get-credential-trustmark.ts
- Added WIA expiration time check
- Fixed inverted `sub` and `subtyp` in payload
> fix: [SIW-1864] Fix trustmark payload

- package.json
This PR bumps the package version to v0.25.0.
> chore: Release v0.25.0

- package.json
This PR bumps the package version to v0.26.0.
> chore: Release v0.26.0

- example/src/utils/openUrlAndListenForRedirect.ts
- src/credential/issuance/05-authorize-access.ts
- src/credential/issuance/06-obtain-credential.ts
- src/credential/issuance/errors.ts
- src/credential/status/02-status-attestation.ts
- src/wallet-instance-attestation/issuing.ts
- Removed `OperationAbortedError`
- Updated comments
This PR removes errors that are no longer needed after #152.
> chore: [SIW-1875] Remove unnecessary error classes

- package.json
This PR bumps the package version to v0.27.0.
> chore: Release v0.27.0

- example/src/thunks/presentation.ts
- src/credential/presentation/04-retrieve-rp-jwks.ts
- src/credential/presentation/08-send-authorization-response.ts
Make context optional for steps 04 and 08.
Make context and appfetch optional in the presentation flow.
> feat: [WLEO-235] Remove required context from presentation flow

- example/src/thunks/presentation.ts
- src/credential/presentation/03-get-request-object.ts
- src/credential/presentation/README.md
- Remove DPoP from the request object during the presentation;
This is a leftover from the previous implementation and isn't supposed to be there according to 0.8.0 specs.
Test a presentation flow.
> chore: Remove DPoP in presentation request object

- src/credential/presentation/07-evaluate-input-descriptor.ts
- src/credential/presentation/__tests__/06-fetch-presentation-definition.test.ts
- src/credential/presentation/__tests__/07-evaluate-input-descriptor.test.ts
This PR aims to fix a wrong addition to optional disclosures during evalution of presesentation_definition
> fix: [WLEO-2218] Remove adding wrong disclosure on optional list

- src/credential/issuance/06-obtain-credential.ts
- src/credential/issuance/types.ts
Change authorization_details schema with array format
This PR aims to fix a new issues about obtaining PID process. It was caused because authorization_details did not follow OID4VCI spec.
> fix: Align authorization_details to OID4VCI spec

- example/src/navigator/MainStackNavigator.tsx
- example/src/screens/PresentationScreen.tsx
- example/src/screens/QrScannerScreen.tsx
- example/src/store/reducers/presentation.ts
- example/src/thunks/presentation.ts
- example/src/thunks/types.ts
- src/credential/presentation/08-send-authorization-response.ts
- src/credential/presentation/__tests__/08-send-authorization-response.test.ts
- src/credential/presentation/index.ts
- src/credential/presentation/types.ts
Added functionality to refuse presentation of a certain credential to an RP by sending an `access_denied` error message
- `src/credential/presentation.ts` :
Added an ErrorResponse type that models an enum with the [OpenID4VP admissible error response codes](https://openid.github.io/OpenID4VP/openid-4-verifiable-presentations-wg-draft.html#name-error-response).
- `src/credential/presentation/08-send-authorization-response.ts` :
Added `SetAuthorizationErrorResponse` type and `sendAuthorizationErrorResponse` method to send an `access_denied` error code in case a user might not want to share all the credential details to the requestor RP.
- Remaining changes are linked to the ones listed above.
- `example/src/thunks/types.ts` :
Add new `RemotePresentationBehavior` type to model the ability to …
> feat: [WLEO-254] Add API for OID4VP Presentation refusal

- package.json
> chore: Release v0.28.0

- example/ios/IoReactNativeWalletExample/AppDelegate.mm
Added the native function to handle deep links since it was removed and CIE ID L2 flow is not working anymore
Test a complete flow using CIE ID auth on the PID request
> fix(example): re-add deep link handler for ios

- package.json
This PR bumps the package version to v0.28.2
> chore: Release 0.28.2

- example/ios/Podfile.lock
- example/package.json
- example/src/thunks/presentation.ts
- example/yarn.lock
- package.json
- src/credential/presentation/07-evaluate-input-descriptor.ts
- src/credential/presentation/__tests__/07-evaluate-input-descriptor.test.ts
- src/credential/presentation/types.ts
- src/mdoc/index.ts
- src/sd-jwt/index.ts
- yarn.lock
This PR updates the library's dependencies, bringing new functionalities and fixing minor issues. In particular, it refactors the prepare vp_token for mdoc format.
- `package.json`, `yarn.lock` : Updated `io-react-native-cbor` version to `1.2.4`, whitelisted dependency from `jest` transform.
- `example/package.json`, `example/yarn.lock` : Updated `io-react-native-cbor` version to `1.2.3`
- Refactored the Presentation object to carry full `EvaluatedDisclosure` objects (instead of plain strings)
- Updated how `prepareRemotePresentations` and `prepareVpToken` handle requestedClaims
- Refactored how requested fields are mapped for selective disclosure in `prepareVpTokenMdoc`, supporting nested claims with namespaces
The dependencies' updates bring to the library a refinement and iOS …
> feat: [WLEO-370] Update library dependencies adapting vpToken in mdoc format

- package.json
This PR bumps the package version to `v0.30.0`
> chore: Release 0.30.0

- package.json
Bumped version to `2.0.0-next.4`
> chore: release `2.0.0-next.4`

- package.json
Bump version to `2.0.0-next.5`.
> chore: release `2.0.0-next.5`

- example/ios/Podfile.lock
- example/package.json
- example/src/screens/ProximityScreen.tsx
- example/yarn.lock
- package.json
- yarn.lock
⚠️ Work only on iOS.
Add RP auth verification
> fix: Upgrade proximity to 0.2.0

- package.json
Bump version to `2.0.0-next.7`.
> chore: release `2.0.0-next.7`
